GMAIL_USERNAME: 'teamcarerus@gmail.com'
PASSWORD: 'wiimod100'
RECAPTCHA_SITE_KEY: '6LcClH4UAAAAAKbSnB9Ceranl0YCIBaqUFuwcTLc'
RECAPTCHA_SECRET_KEY: '6LcClH4UAAAAAAeR9IMLEEfRSPuMA6Mfw5spSg1j'
WELCOME_EMAIL: 'welcome@teamcarer.com'
WELCOME_EMAIL_PASSWORD: '5)MilkStreet'
STRIPE_PUBLISHABLE_KEY: 'pk_test_QKmjOKhBDVYrIbtrmyMKHGc3'
STRIPE_SECRET_KEY: 'sk_test_saEXhD4iBbhrElnlndhQlSQk'